Repository kakao-tech-campus-2nd-step3/Team5_FE, pull requests merged in 2024-09, with the labels that each got.

#8 스토리북 세팅하기
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
Labels: 📦 Environment

#7 절대경로 인식 불가 이슈 해결
  src/main.tsx
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 🐛 BugFix, 📦 Environment

#9 MSW 환경 세팅
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  public/vite.svg
  src/main.tsx
  src/mocks/browser.ts
  tsconfig.json
Labels: 📦 Environment

#3 추가 프로젝트 환경 세팅
  .github/ISSUE_TEMPLATE/ISSUE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/App.css
  src/App.tsx
  src/assets/.gitkeep
  src/components/common/AsyncBoundary/.gitkeep
  src/components/common/Spinner/.gitkeep
  src/components/common/button/.gitkeep
  src/components/common/form/.gitkeep
  src/components/common/img/.gitkeep
  src/components/common/input/.gitkeep
  src/components/common/layer/.gitkeep
  src/components/common/typography/.gitkeep
  src/components/feature/footer/.gitkeep
  src/components/feature/header/.gitkeep
  src/components/feature/modal/.gitkeep
  src/constants/.gitkeep
  src/main.tsx
  src/mocks/.gitkeep
  src/mocks/browser.ts
  src/pages/.gitkeep
  src/router/.gitkeep
  src/store/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 📦 Environment

#11 [Review] 3주차 코드 리뷰 PR
  .github/ISSUE_TEMPLATE/ISSUE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/App.css
  src/App.tsx
  src/assets/.gitkeep
  src/components/common/AsyncBoundary/.gitkeep
  src/components/common/Spinner/.gitkeep
  src/components/common/button/.gitkeep
  src/components/common/form/.gitkeep
  src/components/common/img/.gitkeep
  src/components/common/input/.gitkeep
  src/components/common/layer/.gitkeep
  src/components/common/typography/.gitkeep
  src/components/feature/footer/.gitkeep
  src/components/feature/header/.gitkeep
  src/components/feature/modal/.gitkeep
  src/constants/.gitkeep
  src/main.tsx
  src/mocks/.gitkeep
  src/mocks/browser.ts
  src/pages/.gitkeep
  src/router/.gitkeep
  src/store/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 📦 Environment, 📌 Review

#14 공용 컴포넌트 구현
  components.json
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.css
  src/components/common/AsyncBoundary/.gitkeep
  src/components/common/AsyncBoundary/index.tsx
  src/components/common/Spinner/.gitkeep
  src/components/common/avatar/index.stories.tsx
  src/components/common/avatar/index.tsx
  src/components/common/button/.gitkeep
  src/components/common/button/index.stories.tsx
  src/components/common/button/index.tsx
  src/components/common/form/.gitkeep
  src/components/common/img/.gitkeep
  src/components/common/img/LazyLoadingImg.tsx
  src/components/common/input/.gitkeep
  src/components/common/input/index.stories.ts
  src/components/common/input/index.tsx
  src/components/common/layer/.gitkeep
  src/components/common/select/index.stories.tsx
  src/components/common/select/index.tsx
  src/components/common/spinner/index.tsx
  src/components/common/textarea/index.tsx
  src/components/common/typography/.gitkeep
  src/components/common/view/LoadingView.tsx
  src/lib/utils.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature

#16 공용 컴포넌트 구현 및 라우터 설정 완료
  components.json
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.css
  src/App.tsx
  src/components/common/AsyncBoundary/.gitkeep
  src/components/common/AsyncBoundary/index.tsx
  src/components/common/Spinner/.gitkeep
  src/components/common/avatar/index.stories.tsx
  src/components/common/avatar/index.tsx
  src/components/common/button/.gitkeep
  src/components/common/button/index.stories.tsx
  src/components/common/button/index.tsx
  src/components/common/form/.gitkeep
  src/components/common/img/.gitkeep
  src/components/common/img/LazyLoadingImg.tsx
  src/components/common/input/.gitkeep
  src/components/common/input/index.stories.ts
  src/components/common/input/index.tsx
  src/components/common/layer/.gitkeep
  src/components/common/select/index.stories.tsx
  src/components/common/select/index.tsx
  src/components/common/spinner/index.tsx
  src/components/common/textarea/index.tsx
  src/components/common/typography/.gitkeep
  src/components/common/view/LoadingView.tsx
  src/lib/utils.ts
  src/main.tsx
  src/mocks/.gitkeep
  src/mocks/Browser.ts
  src/pages/.gitkeep
  src/pages/ErrorPage.tsx
  src/pages/RootPage.tsx
  src/pages/main/index.tsx
  src/router/.gitkeep
  src/router/Router.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 🔧 Chore

#17 [Master] 4주차 코드 Master 에 병합
  components.json
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.css
  src/App.tsx
  src/components/common/AsyncBoundary/.gitkeep
  src/components/common/AsyncBoundary/index.tsx
  src/components/common/Spinner/.gitkeep
  src/components/common/avatar/index.stories.tsx
  src/components/common/avatar/index.tsx
  src/components/common/button/.gitkeep
  src/components/common/button/index.stories.tsx
  src/components/common/button/index.tsx
  src/components/common/form/.gitkeep
  src/components/common/img/.gitkeep
  src/components/common/img/LazyLoadingImg.tsx
  src/components/common/input/.gitkeep
  src/components/common/input/index.stories.ts
  src/components/common/input/index.tsx
  src/components/common/layer/.gitkeep
  src/components/common/select/index.stories.tsx
  src/components/common/select/index.tsx
  src/components/common/spinner/index.tsx
  src/components/common/textarea/index.tsx
  src/components/common/typography/.gitkeep
  src/components/common/view/LoadingView.tsx
  src/lib/utils.ts
  src/main.tsx
  src/mocks/.gitkeep
  src/mocks/Browser.ts
  src/pages/.gitkeep
  src/pages/ErrorPage.tsx
  src/pages/RootPage.tsx
  src/pages/main/index.tsx
  src/router/.gitkeep
  src/router/Router.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 🔄 Merge
