Repository kakao-tech-campus-2nd-step3/Team5_FE, pull requests merged in 2024-11, with the labels that each got.

#49 무한 스크롤을 이용한 쇼츠 시청 페이지 (Viewer) 구현
  package.json
  pnpm-lock.yaml
  src/pages/viewer/hooks/useFetchShorts.ts
  src/pages/viewer/index.tsx
  src/router/index.tsx
  src/router/path.ts
Labels: ✨ Feature

#50 [Develop] 추가 정보 입력 / 쇼츠 시청 페이지 구현 완료
  package.json
  pnpm-lock.yaml
  src/components/common/button/index.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/add/components/field/AddInformField.tsx
  src/pages/add/components/field/AgeField.tsx
  src/pages/add/components/field/CategoriesField.tsx
  src/pages/add/components/field/GenderField.tsx
  src/pages/add/components/field/index.tsx
  src/pages/add/components/form/AddForm.tsx
  src/pages/add/components/form/index.tsx
  src/pages/add/components/index.ts
  src/pages/add/index.tsx
  src/pages/add/utils/AddSchema.ts
  src/pages/add/utils/index.ts
  src/pages/myPage/index.tsx
  src/pages/viewer/hooks/useFetchShorts.ts
  src/pages/viewer/index.tsx
  src/router/index.tsx
  src/router/path.ts
Labels: ✨ Feature, 🔧 Chore

#52 쇼츠 시청 페이지 코드 스플리팅
  src/pages/viewer/api/useFetchShorts.api.ts
  src/pages/viewer/components/ShortsCard.tsx
  src/pages/viewer/index.tsx
Labels: ♻️ Refactoring, 🔧 Chore

#51 [Master] 9주차 코드 Master에 병합
  package.json
  pnpm-lock.yaml
  src/components/common/button/index.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/add/components/field/AddInformField.tsx
  src/pages/add/components/field/AgeField.tsx
  src/pages/add/components/field/CategoriesField.tsx
  src/pages/add/components/field/GenderField.tsx
  src/pages/add/components/field/index.tsx
  src/pages/add/components/form/AddForm.tsx
  src/pages/add/components/form/index.tsx
  src/pages/add/components/index.ts
  src/pages/add/index.tsx
  src/pages/add/utils/AddSchema.ts
  src/pages/add/utils/index.ts
  src/pages/myPage/index.tsx
  src/pages/viewer/api/useFetchShorts.api.ts
  src/pages/viewer/components/ShortsCard.tsx
  src/pages/viewer/index.tsx
  src/router/index.tsx
  src/router/path.ts
Labels: 🔄 Merge

#55 유튜브 url 검증
  package.json
  pnpm-lock.yaml
  src/apis/instance/Instance.api.ts
  src/constants/.gitkeep
  src/constants/URI.ts
  src/mocks/Browser.ts
  src/mocks/browser.ts
  src/mocks/handlers/auto/AutoHandler.ts
  src/mocks/handlers/auto/index.ts
  src/mocks/handlers/index.ts
  src/pages/auto/apis/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/auto/components/card/LinkCard.tsx
  src/pages/auto/components/field/LinkField.tsx
  src/pages/auto/components/form/ConvertForm.tsx
  src/pages/auto/provider/LinkProvider.tsx
  src/pages/auto/provider/index.ts
Labels: ✨ Feature, 👽 API

#57 테스트코드 및 msw 테스트 코드 환경세팅
  babel.config.cjs
  jest.config.cjs
  jest.setup.cjs
  package.json
  pnpm-lock.yaml
  src/mocks/Server.ts
  src/setupTest.ts
  tsconfig.jest.json
  tsconfig.json
Labels: 📦 Environment, ✅ TestCode

#53 [Review] 9주차 코드 리뷰 PR
  package.json
  pnpm-lock.yaml
  src/components/common/button/index.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/add/components/field/AddInformField.tsx
  src/pages/add/components/field/AgeField.tsx
  src/pages/add/components/field/CategoriesField.tsx
  src/pages/add/components/field/GenderField.tsx
  src/pages/add/components/field/index.tsx
  src/pages/add/components/form/AddForm.tsx
  src/pages/add/components/form/index.tsx
  src/pages/add/components/index.ts
  src/pages/add/index.tsx
  src/pages/add/utils/AddSchema.ts
  src/pages/add/utils/index.ts
  src/pages/myPage/index.tsx
  src/pages/viewer/api/useFetchShorts.api.ts
  src/pages/viewer/components/ShortsCard.tsx
  src/pages/viewer/index.tsx
  src/router/index.tsx
  src/router/path.ts
Labels: 📌 Review

#59 카테고리 별 영상 불러오기 MSW 코드 작성
  package.json
  pnpm-lock.yaml
  src/apis/instance/Instance.api.ts
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/grid/ShortsGrid.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/main/FetchShortsHandler.ts
  src/mocks/handlers/main/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/main/apis/fetchShortsList.api.ts
  src/pages/main/index.tsx
  src/pages/main/utils/Category.ts
  src/router/index.tsx
  src/router/path.ts
Labels: ✨ Feature, 👽 API

#61 9주차 코드 리팩토링하기
  src/components/feature/button/CategoriesBtn.tsx
  src/components/feature/index.ts
  src/pages/add/components/field/AgeField.tsx
  src/pages/add/components/field/CategoriesField.tsx
  src/pages/add/components/field/GenderField.tsx
  src/pages/auto/components/field/CategoryField.tsx
Labels: ♻️ Refactoring

#62 [Develop] 유투브 URL validation / 카테고리 별 영상 불러오기 MSW 코드 작성
  babel.config.cjs
  jest.config.cjs
  jest.setup.cjs
  package.json
  pnpm-lock.yaml
  src/apis/instance/Instance.api.ts
  src/components/feature/button/CategoriesBtn.tsx
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/index.ts
  src/constants/.gitkeep
  src/constants/URI.ts
  src/mocks/Browser.ts
  src/mocks/Server.ts
  src/mocks/browser.ts
  src/mocks/handlers/auto/AutoHandler.ts
  src/mocks/handlers/auto/index.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/main/FetchShortsHandler.ts
  src/mocks/handlers/main/index.ts
  src/pages/add/components/field/AgeField.tsx
  src/pages/add/components/field/CategoriesField.tsx
  src/pages/add/components/field/GenderField.tsx
  src/pages/auto/apis/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/auto/components/card/LinkCard.tsx
  src/pages/auto/components/field/CategoryField.tsx
  src/pages/auto/components/field/LinkField.tsx
  src/pages/auto/components/form/ConvertForm.tsx
  src/pages/auto/provider/LinkProvider.tsx
  src/pages/auto/provider/index.ts
  src/pages/main/apis/fetchShortsList.api.ts
  src/pages/main/index.tsx
  src/pages/main/utils/Category.ts
  src/router/index.tsx
  src/router/path.ts
  src/setupTest.ts
  tsconfig.jest.json
  tsconfig.json
Labels: ✨ Feature, 📦 Environment, 👽 API

#63 [Master] 10주차 코드 Master 에 병합
  babel.config.cjs
  jest.config.cjs
  jest.setup.cjs
  package.json
  pnpm-lock.yaml
  src/apis/instance/Instance.api.ts
  src/components/feature/button/CategoriesBtn.tsx
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/index.ts
  src/constants/.gitkeep
  src/constants/URI.ts
  src/mocks/Browser.ts
  src/mocks/Server.ts
  src/mocks/browser.ts
  src/mocks/handlers/auto/AutoHandler.ts
  src/mocks/handlers/auto/index.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/main/FetchShortsHandler.ts
  src/mocks/handlers/main/index.ts
  src/pages/add/components/field/AgeField.tsx
  src/pages/add/components/field/CategoriesField.tsx
  src/pages/add/components/field/GenderField.tsx
  src/pages/auto/apis/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/auto/components/card/LinkCard.tsx
  src/pages/auto/components/field/CategoryField.tsx
  src/pages/auto/components/field/LinkField.tsx
  src/pages/auto/components/form/ConvertForm.tsx
  src/pages/auto/provider/LinkProvider.tsx
  src/pages/auto/provider/index.ts
  src/pages/main/apis/fetchShortsList.api.ts
  src/pages/main/index.tsx
  src/pages/main/utils/Category.ts
  src/router/index.tsx
  src/router/path.ts
  src/setupTest.ts
  tsconfig.jest.json
  tsconfig.json
Labels: 🔄 Merge

#65 로그인 이후 추가정보 입력하기 파트 msw 코드 및 api 구현
  src/apis/index.ts
  src/apis/instance/index.ts
  src/mocks/handlers/auto/index.ts
  src/mocks/handlers/index.ts
  src/pages/add/apis/index.ts
  src/pages/add/apis/postAddInfo.api.ts
  src/pages/add/components/form/AddForm.tsx
  src/pages/add/mocks/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/auto/mocks/index.ts
Labels: ✨ Feature

#67 코드 리팩토링 및 수정
  src/apis/instance/index.ts
  src/components/feature/button/index.ts
  src/components/feature/card/index.ts
  src/components/feature/grid/index.ts
  src/components/feature/index.ts
  src/components/feature/menu/index.ts
  src/components/feature/sidebar/index.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/main/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/auto/components/process/Process.tsx
  src/pages/main/apis/index.ts
  src/pages/main/index.tsx
  src/pages/main/mocks/index.ts
  src/pages/main/utils/index.ts
  src/pages/myPage/utils/index.ts
Labels: ♻️ Refactoring

#68 Week10
  src/apis/index.ts
  src/apis/instance/index.ts
  src/components/feature/button/index.ts
  src/components/feature/card/index.ts
  src/components/feature/grid/index.ts
  src/components/feature/index.ts
  src/components/feature/menu/index.ts
  src/components/feature/sidebar/index.tsx
  src/mocks/handlers/auto/index.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/main/index.ts
  src/pages/add/apis/index.ts
  src/pages/add/apis/postAddInfo.api.ts
  src/pages/add/components/form/AddForm.tsx
  src/pages/add/mocks/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/auto/components/process/Process.tsx
  src/pages/auto/mocks/index.ts
  src/pages/main/apis/index.ts
  src/pages/main/index.tsx
  src/pages/main/mocks/index.ts
  src/pages/main/utils/index.ts
  src/pages/myPage/utils/index.ts
Labels: ✨ Feature, ♻️ Refactoring

#69 [Master] 로그인 이후 추가 정보 입력 msw 코드 및 api 코드 추가, 추가 코드 모듈화 및 코드 리팩토링
  src/apis/index.ts
  src/apis/instance/index.ts
  src/components/feature/button/index.ts
  src/components/feature/card/index.ts
  src/components/feature/grid/index.ts
  src/components/feature/index.ts
  src/components/feature/menu/index.ts
  src/components/feature/sidebar/index.tsx
  src/mocks/handlers/auto/index.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/main/index.ts
  src/pages/add/apis/index.ts
  src/pages/add/apis/postAddInfo.api.ts
  src/pages/add/components/form/AddForm.tsx
  src/pages/add/mocks/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/auto/components/process/Process.tsx
  src/pages/auto/mocks/index.ts
  src/pages/main/apis/index.ts
  src/pages/main/index.tsx
  src/pages/main/mocks/index.ts
  src/pages/main/utils/index.ts
  src/pages/myPage/utils/index.ts
Labels: ✨ Feature, ♻️ Refactoring

#74 페이지 별 MSW 연결 및 디자인 수정
  package.json
  pnpm-lock.yaml
  src/assets/Sample_video.mp4
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/sidebar/index.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/viewer/FetchCommentsHandler.ts
  src/mocks/handlers/viewer/PostCommentsHandler.ts
  src/mocks/handlers/viewer/ViewShortsHandler.ts
  src/mocks/handlers/viewer/index.ts
  src/pages/main/index.tsx
  src/pages/viewer/api/useFetchShorts.api.ts
  src/pages/viewer/apis/useCreateComment.api.ts
  src/pages/viewer/apis/useFetchComments.api.ts
  src/pages/viewer/apis/useFetchShorts.api.ts
  src/pages/viewer/components/Comments.style.ts
  src/pages/viewer/components/Comments.tsx
  src/pages/viewer/components/ShortsCard.style.ts
  src/pages/viewer/components/ShortsCard.tsx
  src/pages/viewer/index.tsx
Labels: ✨ Feature, ♻️ Refactoring, 👽 API

#77 mock 파일 경로 변경 및 오타 수정
  src/mocks/handlers/index.ts
  src/mocks/handlers/viewer/FetchCommentsHandler.ts
  src/mocks/handlers/viewer/PostCommentsHandler.ts
  src/mocks/handlers/viewer/ViewShortsHandler.ts
  src/mocks/handlers/viewer/index.ts
  src/pages/add/apis/postAddInfo.api.ts
  src/pages/viewer/mocks/index.ts
Labels: 🔥 Remove, 🔧 Chore

#64 [Review] 10주차 코드 리뷰
  babel.config.cjs
  jest.config.cjs
  jest.setup.cjs
  package.json
  pnpm-lock.yaml
  src/apis/index.ts
  src/apis/instance/Instance.api.ts
  src/apis/instance/index.ts
  src/components/feature/button/CategoriesBtn.tsx
  src/components/feature/button/index.ts
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/card/index.ts
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/grid/index.ts
  src/components/feature/index.ts
  src/components/feature/menu/index.ts
  src/components/feature/sidebar/index.tsx
  src/constants/.gitkeep
  src/constants/URI.ts
  src/mocks/Browser.ts
  src/mocks/Server.ts
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/pages/add/apis/index.ts
  src/pages/add/apis/postAddInfo.api.ts
  src/pages/add/components/field/AgeField.tsx
  src/pages/add/components/field/CategoriesField.tsx
  src/pages/add/components/field/GenderField.tsx
  src/pages/add/components/form/AddForm.tsx
  src/pages/add/mocks/index.ts
  src/pages/auto/apis/index.ts
  src/pages/auto/apis/postValidateUrl.api.ts
  src/pages/auto/components/card/LinkCard.tsx
  src/pages/auto/components/field/CategoryField.tsx
  src/pages/auto/components/field/LinkField.tsx
  src/pages/auto/components/form/ConvertForm.tsx
  src/pages/auto/components/process/Process.tsx
  src/pages/auto/mocks/index.ts
  src/pages/auto/provider/LinkProvider.tsx
  src/pages/auto/provider/index.ts
  src/pages/main/apis/fetchShortsList.api.ts
  src/pages/main/apis/index.ts
  src/pages/main/index.tsx
  src/pages/main/mocks/index.ts
  src/pages/main/utils/Category.ts
  src/pages/main/utils/index.ts
  src/pages/myPage/utils/index.ts
  src/router/index.tsx
  src/router/path.ts
  src/setupTest.ts
  tsconfig.jest.json
  tsconfig.json
Labels: 📌 Review

#80 vitest 환경세팅
  babel.config.cjs
  jest.config.cjs
  jest.setup.cjs
  package.json
  pnpm-lock.yaml
  src/setupTest.ts
  tsconfig.jest.json
  tsconfig.json
  vite.config.ts
Labels: 🐛 BugFix, 📦 Environment, ✅ TestCode, 🔧 Chore

#84 특정 영상 불러오기 / 댓글 / 내 정보 수정 API 연결
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/sidebar/index.tsx
  src/mocks/handlers/index.ts
  src/pages/main/apis/fetchShortsList.ts
  src/pages/main/index.tsx
  src/pages/myPage/apis/fetchMyInfo.ts
  src/pages/myPage/apis/updateMyInfo.ts
  src/pages/myPage/components/Header.tsx
  src/pages/myPage/components/MyInfoDisplay.tsx
  src/pages/myPage/components/ProfileEditField.tsx
  src/pages/myPage/components/ProfileEditForm.tsx
  src/pages/myPage/components/VideoManagement.tsx
  src/pages/myPage/index.tsx
  src/pages/myPage/utils/ProfileSchema.ts
  src/pages/viewer/apis/comments/createComment.ts
  src/pages/viewer/apis/comments/deleteComment.ts
  src/pages/viewer/apis/comments/fetchComments.ts
  src/pages/viewer/apis/comments/updateComment.ts
  src/pages/viewer/apis/reactions/likeVideo.ts
  src/pages/viewer/apis/shorts/fetchShortsDetail.ts
  src/pages/viewer/apis/useCreateComment.api.ts
  src/pages/viewer/apis/useFetchShorts.api.ts
  src/pages/viewer/components/CommentItem.tsx
  src/pages/viewer/components/Comments.tsx
  src/pages/viewer/components/CommentsContainer.style.ts
  src/pages/viewer/components/CommentsContainer.tsx
  src/pages/viewer/components/ShortsCard.tsx
  src/pages/viewer/hooks/useComments.ts
  src/pages/viewer/index.tsx
  src/pages/viewer/mocks/index.ts
Labels: 👽 API

#86 개발환경 및 영상 추출 api 구현
  .eslintignore
  .eslintrc.json
  .github/workflows/deploy.yml
  components.json
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/App.css
  src/apis/instance/Instance.api.ts
  src/apis/instance/InstanceFast.api.ts
  src/components/common/avatar/index.tsx
  src/components/common/card/index.tsx
  src/components/common/index.ts
  src/components/common/label/index.tsx
  src/components/common/progress/index.tsx
  src/components/common/select/index.tsx
  src/components/common/skeleton/index.tsx
  src/components/common/status_dot/index.stories.ts
  src/components/common/status_dot/index.tsx
  src/components/common/textarea/index.tsx
  src/components/common/tooltip/index.tsx
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/sidebar/index.tsx
  src/hooks/index.tsx
  src/hooks/usePreventRefresh.ts
  src/lib/utils.ts
  src/pages/ErrorPage.tsx
  src/pages/auto/apis/fetchSelectHighLight.api.ts
  src/pages/auto/apis/fetchTaskStatus.ts
  src/pages/auto/apis/fetchVideoExtract.api.ts
  src/pages/auto/apis/index.ts
  src/pages/auto/apis/postConvertForm.api.ts
  src/pages/auto/apis/postHighlightSelection.api.ts
  src/pages/auto/components/button/InitBtn.tsx
  src/pages/auto/components/button/index.tsx
  src/pages/auto/components/card/LinkCard.tsx
  src/pages/auto/components/field/LinkField.tsx
  src/pages/auto/components/final/ConvertShorts.tsx
  src/pages/auto/components/final/FinalView.tsx
  src/pages/auto/components/form/ConvertForm.tsx
  src/pages/auto/components/index.ts
  src/pages/auto/components/loading/Loading.tsx
  src/pages/auto/components/loading/ProgressView.tsx
  src/pages/auto/components/video/ShortsVideo.tsx
  src/pages/auto/components/video/index.tsx
  src/pages/auto/index.tsx
  src/pages/myPage/index.tsx
  src/pages/redirect/index.tsx
  src/pages/viewer/apis/comments/fetchComments.ts
  tsconfig.json
Labels: 🐛 BugFix, 🚀 Deploy, ✨ Feature, 👽 API

#88 api 업로드 및 쇼츠 추출화면 구현
  .github/workflows/deploy.yml
  index.html
  public/Logo.png
  src/apis/instance/Instance.api.ts
  src/apis/instance/InstanceFast.api.ts
  src/pages/auto/apis/form/postConvertForm.api.ts
  src/pages/auto/apis/form/postValidateUrl.api.ts
  src/pages/auto/apis/index.ts
  src/pages/auto/apis/progress/fetchTaskStatus.ts
  src/pages/auto/apis/select/fetchSelectHighLight.api.ts
  src/pages/auto/apis/select/fetchVideoExtract.api.ts
  src/pages/auto/apis/select/postHighlightSelection.api.ts
  src/pages/auto/components/final/FinalView.tsx
  src/pages/auto/components/loading/ProgressView.tsx
  src/styles/.gitkeep
  src/types/.gitkeep
Labels: 🐛 BugFix, ✨ Feature, 👽 API, 🔧 Chore

#92 ngrok skip cors config header 추가
  src/apis/instance/InstanceFast.api.ts
Labels: 🐛 BugFix, 🚑 !HOTFIX
