Repository kakao-tech-campus-2nd-step3/Team5_FE, pull requests merged in 2024-10, with the labels that each got.

#21 헤더 컴포넌트 구현
  src/App.tsx
  src/components/common/input/index.tsx
  src/components/feature/header/.gitkeep
  src/components/feature/header/index.tsx
  src/pages/RootPage.tsx
Labels: ✨ Feature

#22 사이드바 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/assets/.gitkeep
  src/assets/Logo.png
  src/components/common/button/index.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/RootPage.tsx
Labels: ✨ Feature

#23 [Develop] 헤더 / 사이드바 컴포넌트 구현 완료
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/assets/.gitkeep
  src/assets/Logo.png
  src/components/common/button/index.tsx
  src/components/common/input/index.tsx
  src/components/feature/header/.gitkeep
  src/components/feature/header/index.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/RootPage.tsx
Labels: ✨ Feature

#28 쇼츠 썸네일 카드 및 그리드 컴포넌트 구현
  src/assets/shorts_img.png
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/grid/ShortsGrid.tsx
  src/pages/main/index.tsx
Labels: ✨ Feature

#29 쇼츠 자동화 페이지 입력 폼 받는 부분 구현
  components.json
  package.json
  pnpm-lock.yaml
  src/components/common/AspectRatio/index.tsx
  src/components/common/AsyncBoundary/index.tsx
  src/components/common/card/index.tsx
  src/components/common/form/index.tsx
  src/components/common/index.ts
  src/components/common/label/index.tsx
  src/components/common/progress/index.tsx
  src/components/feature/index.ts
  src/components/index.ts
  src/pages/auto/components/ConvertField.tsx
  src/pages/auto/components/ConvertForm.tsx
  src/pages/auto/components/LinkCard.tsx
  src/pages/auto/components/Progress.tsx
  src/pages/auto/index.tsx
  src/pages/auto/utils/FormSchema.ts
  src/pages/main/index.tsx
  src/router/Router.tsx
Labels: ✨ Feature

#32 컴포넌트 모듈화
  src/components/feature/card/index.ts
  src/components/feature/footer/.gitkeep
  src/components/feature/grid/index.ts
  src/components/feature/index.ts
  src/components/feature/modal/.gitkeep
  src/pages/main/index.tsx
Labels: ✨ Feature, 🔧 Chore

#31 [Develop] 쇼츠 썸네일 및 쇼츠 자동화 페이지 구현 완료 / 코드 모듈화 진행
  components.json
  package.json
  pnpm-lock.yaml
  src/assets/shorts_img.png
  src/components/common/AspectRatio/index.tsx
  src/components/common/AsyncBoundary/index.tsx
  src/components/common/card/index.tsx
  src/components/common/form/index.tsx
  src/components/common/index.ts
  src/components/common/label/index.tsx
  src/components/common/progress/index.tsx
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/card/index.ts
  src/components/feature/footer/.gitkeep
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/grid/index.ts
  src/components/feature/index.ts
  src/components/feature/modal/.gitkeep
  src/components/feature/sidebar/index.tsx
  src/components/index.ts
  src/pages/auto/components/ConvertField.tsx
  src/pages/auto/components/ConvertForm.tsx
  src/pages/auto/components/LinkCard.tsx
  src/pages/auto/components/Progress.tsx
  src/pages/auto/index.tsx
  src/pages/auto/utils/FormSchema.ts
  src/pages/main/index.tsx
  src/router/Router.tsx
Labels: ✨ Feature

#33 [Master] 6주차 코드 Master 에 병합
  components.json
  package.json
  pnpm-lock.yaml
  src/assets/shorts_img.png
  src/components/common/AspectRatio/index.tsx
  src/components/common/AsyncBoundary/index.tsx
  src/components/common/card/index.tsx
  src/components/common/form/index.tsx
  src/components/common/index.ts
  src/components/common/label/index.tsx
  src/components/common/progress/index.tsx
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/card/index.ts
  src/components/feature/footer/.gitkeep
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/grid/index.ts
  src/components/feature/index.ts
  src/components/feature/modal/.gitkeep
  src/components/feature/sidebar/index.tsx
  src/components/index.ts
  src/pages/auto/components/ConvertField.tsx
  src/pages/auto/components/ConvertForm.tsx
  src/pages/auto/components/LinkCard.tsx
  src/pages/auto/components/Progress.tsx
  src/pages/auto/index.tsx
  src/pages/auto/utils/FormSchema.ts
  src/pages/main/index.tsx
  src/router/Router.tsx
Labels: ✨ Feature

#35 코드 모듈화시키기
  src/App.tsx
  src/components/common/index.ts
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/card/index.ts
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/grid/index.ts
  src/components/feature/header/index.tsx
  src/components/feature/index.ts
  src/components/feature/sidebar/index.tsx
  src/pages/auto/components/ConvertForm.tsx
  src/pages/auto/components/LinkCard.tsx
  src/pages/auto/components/index.ts
  src/pages/auto/index.tsx
  src/pages/auto/utils/index.ts
  src/router/index.tsx
  src/router/path.ts
  src/store/.gitkeep
Labels: ♻️ Refactoring

#37 코드 모듈화 및 쇼츠 영상 자동화 API 미제외 구현 완료
  src/assets/convert_img.png
  src/components/common/progress/index.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/RootPage.tsx
  src/pages/auto/components/ConvertField.tsx
  src/pages/auto/components/Progress.tsx
  src/pages/auto/components/card/LinkCard.tsx
  src/pages/auto/components/card/index.ts
  src/pages/auto/components/field/CategoryField.tsx
  src/pages/auto/components/field/ConvertField.tsx
  src/pages/auto/components/field/KeywordsField.tsx
  src/pages/auto/components/field/LinkField.tsx
  src/pages/auto/components/field/TitleField.tsx
  src/pages/auto/components/field/index.ts
  src/pages/auto/components/final/ConvertShorts.tsx
  src/pages/auto/components/final/FinalView.tsx
  src/pages/auto/components/final/index.ts
  src/pages/auto/components/form/ConvertForm.tsx
  src/pages/auto/components/form/index.ts
  src/pages/auto/components/index.ts
  src/pages/auto/components/loading/Loading.tsx
  src/pages/auto/components/loading/ProgressView.tsx
  src/pages/auto/components/loading/index.tsx
  src/pages/auto/components/process/Process.tsx
  src/pages/auto/components/process/index.ts
  src/pages/auto/index.tsx
  src/pages/auto/provider/ProcessProvider.tsx
  src/pages/auto/provider/index.ts
Labels: ✨ Feature

#39 내 정보 수정 (myPage) 페이지 구현
  package.json
  pnpm-lock.yaml
  src/components/feature/header/index.tsx
  src/components/feature/index.ts
  src/components/feature/menu/ProfileMenu.tsx
  src/pages/myPage/components/Header.tsx
  src/pages/myPage/components/MembershipStatus.tsx
  src/pages/myPage/components/ProfileEditField.tsx
  src/pages/myPage/components/ProfileEditForm.tsx
  src/pages/myPage/components/VideoManagement.tsx
  src/pages/myPage/index.tsx
  src/pages/myPage/utils/ProfileSchema.ts
  src/router/index.tsx
  src/router/path.ts
Labels: ✨ Feature

#40 [Develop] 내 정보 수정 / 쇼츠 자동화 페이지 완성
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/assets/convert_img.png
  src/components/common/index.ts
  src/components/common/progress/index.tsx
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/card/index.ts
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/grid/index.ts
  src/components/feature/header/index.tsx
  src/components/feature/index.ts
  src/components/feature/menu/ProfileMenu.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/RootPage.tsx
  src/pages/auto/components/ConvertField.tsx
  src/pages/auto/components/LinkCard.tsx
  src/pages/auto/components/Progress.tsx
  src/pages/auto/components/card/LinkCard.tsx
  src/pages/auto/components/card/index.ts
  src/pages/auto/components/field/CategoryField.tsx
  src/pages/auto/components/field/ConvertField.tsx
  src/pages/auto/components/field/KeywordsField.tsx
  src/pages/auto/components/field/LinkField.tsx
  src/pages/auto/components/field/TitleField.tsx
  src/pages/auto/components/field/index.ts
  src/pages/auto/components/final/ConvertShorts.tsx
  src/pages/auto/components/final/FinalView.tsx
  src/pages/auto/components/final/index.ts
  src/pages/auto/components/form/ConvertForm.tsx
  src/pages/auto/components/form/index.ts
  src/pages/auto/components/index.ts
  src/pages/auto/components/loading/Loading.tsx
  src/pages/auto/components/loading/ProgressView.tsx
  src/pages/auto/components/loading/index.tsx
  src/pages/auto/components/process/Process.tsx
  src/pages/auto/components/process/index.ts
  src/pages/auto/index.tsx
  src/pages/auto/provider/ProcessProvider.tsx
  src/pages/auto/provider/index.ts
  src/pages/auto/utils/index.ts
  src/pages/myPage/components/Header.tsx
  src/pages/myPage/components/MembershipStatus.tsx
  src/pages/myPage/components/ProfileEditField.tsx
  src/pages/myPage/components/ProfileEditForm.tsx
  src/pages/myPage/components/VideoManagement.tsx
  src/pages/myPage/index.tsx
  src/pages/myPage/utils/ProfileSchema.ts
  src/router/index.tsx
  src/router/path.ts
  src/store/.gitkeep
Labels: ✨ Feature, ♻️ Refactoring, 🔧 Chore

#41 [Master] 7주차 코드 Master에 병합
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/assets/convert_img.png
  src/components/common/index.ts
  src/components/common/progress/index.tsx
  src/components/feature/card/ShortsThumbnailCard.tsx
  src/components/feature/card/index.ts
  src/components/feature/grid/ShortsGrid.tsx
  src/components/feature/grid/index.ts
  src/components/feature/header/index.tsx
  src/components/feature/index.ts
  src/components/feature/menu/ProfileMenu.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/RootPage.tsx
  src/pages/auto/components/ConvertField.tsx
  src/pages/auto/components/LinkCard.tsx
  src/pages/auto/components/Progress.tsx
  src/pages/auto/components/card/LinkCard.tsx
  src/pages/auto/components/card/index.ts
  src/pages/auto/components/field/CategoryField.tsx
  src/pages/auto/components/field/ConvertField.tsx
  src/pages/auto/components/field/KeywordsField.tsx
  src/pages/auto/components/field/LinkField.tsx
  src/pages/auto/components/field/TitleField.tsx
  src/pages/auto/components/field/index.ts
  src/pages/auto/components/final/ConvertShorts.tsx
  src/pages/auto/components/final/FinalView.tsx
  src/pages/auto/components/final/index.ts
  src/pages/auto/components/form/ConvertForm.tsx
  src/pages/auto/components/form/index.ts
  src/pages/auto/components/index.ts
  src/pages/auto/components/loading/Loading.tsx
  src/pages/auto/components/loading/ProgressView.tsx
  src/pages/auto/components/loading/index.tsx
  src/pages/auto/components/process/Process.tsx
  src/pages/auto/components/process/index.ts
  src/pages/auto/index.tsx
  src/pages/auto/provider/ProcessProvider.tsx
  src/pages/auto/provider/index.ts
  src/pages/auto/utils/index.ts
  src/pages/myPage/components/Header.tsx
  src/pages/myPage/components/MembershipStatus.tsx
  src/pages/myPage/components/ProfileEditField.tsx
  src/pages/myPage/components/ProfileEditForm.tsx
  src/pages/myPage/components/VideoManagement.tsx
  src/pages/myPage/index.tsx
  src/pages/myPage/utils/ProfileSchema.ts
  src/router/index.tsx
  src/router/path.ts
  src/store/.gitkeep
Labels: 🔄 Merge

#44 로그인 후 추가 정보 입력란 구현하기
  src/components/common/button/index.tsx
  src/components/feature/sidebar/index.tsx
  src/pages/add/components/field/AddInformField.tsx
  src/pages/add/components/field/AgeField.tsx
  src/pages/add/components/field/CategoriesField.tsx
  src/pages/add/components/field/GenderField.tsx
  src/pages/add/components/field/index.tsx
  src/pages/add/components/form/AddForm.tsx
  src/pages/add/components/form/index.tsx
  src/pages/add/components/index.ts
  src/pages/add/index.tsx
  src/pages/add/utils/AddSchema.ts
  src/pages/add/utils/index.ts
  src/pages/myPage/index.tsx
  src/router/index.tsx
  src/router/path.ts
Labels: ✨ Feature
